//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discuss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discuss()
        {
            this.Dislike = new HashSet<Dislike>();
        }
    
        public int diid { get; set; }
        public int usid { get; set; }
        public string dicount { get; set; }
        public int esid { get; set; }
        public int disliang { get; set; }
        public System.DateTime disdate { get; set; }
    
        public virtual Essay Essay { get; set; }
        public virtual Usersd Usersd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dislike> Dislike { get; set; }
    }
}
