//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eslike
    {
        public int elid { get; set; }
        public int usid { get; set; }
        public System.DateTime eldate { get; set; }
        public int esid { get; set; }
    
        public virtual Essay Essay { get; set; }
        public virtual Usersd Usersd { get; set; }
    }
}
