//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photocuss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photocuss()
        {
            this.Pclike = new HashSet<Pclike>();
        }
    
        public int pcid { get; set; }
        public int usid { get; set; }
        public string pccount { get; set; }
        public int phid { get; set; }
        public int pcliang { get; set; }
        public System.DateTime pcdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pclike> Pclike { get; set; }
        public virtual Phabum Phabum { get; set; }
        public virtual Usersd Usersd { get; set; }
    }
}
